# For more info on HTTP files go to https://aka.ms/vs/httpfile

ET https://localhost:5136/games 

###

GET https://localhost:5136/games/2

###

POST https://localhost:5136/games
content-type: application/json
{
  "name": "Call of Duty: Modern Warfare II",
  "genreId": 2,
  "price": 69.99,
  "releaseDate": "2022-10-28"
}

###


PUT https://localhost:5136/games/7
content-type: application/json
{
  "name": "Updated Game2",
  "genreId": 2,
  "price": 100,
  "releaseDate": "2022-12-01"
}

###

DELETE https://localhost:5136/games/2

